spring:
  application:
    name: eits-data-ingest
  security:
    oauth2:
      client:
        registration:
          opensky:
            client-id: ${OPENSKY_CLIENT_ID}
            client-secret: ${OPENSKY_CLIENT_SECRET}
            authorization-grant-type: client_credentials
        provider:
          opensky:
            token-uri: https://auth.opensky-network.org/auth/realms/opensky-network/protocol/openid-connect/token
  kafka:
    bootstrap-servers: kafka:9092

    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.ByteArraySerializer
      properties:
        acks: all
        retries: 3
opensky:
  endpoint: https://opensky-network.org/api/states/all
  connection-timeout-ms: 100
  read-timeout-ms: 9500

resilience4j.retry:
  instances:
    opensky:
      maxAttempts: 2
      waitDuration: 10s
      enableExponentialBackoff: false
